### ISSUE TITLE
GH Page with demo

### ISSUE THREAD

**Issue by Godoy** [a115/HTML-SVG-connect#4]
Hi there!
First, this is awesome plugin! Congrats :)

I suggest creating a gh-page branch to easier preview the plugin demo in 'index.html'.

Thanks

**Comment by Diego-Soares** [comment]
Will be great!

**Comment by ojlewis** [comment]
According to a recent GitHub blog post: [Publishing with GitHub Pages, now as easy as 1, 2, 3](https://github.com/blog/2289-publishing-with-github-pages-now-as-easy-as-1-2-3);
@a115 if you activate GitHub Pages via the repository's settings (https://github.com/a115/HTML-SVG-connect/settings): scroll down to: **GitHub Pages** > **Source**, and select "master branch". Then the demo will load at: http://a115.github.io/HTML-SVG-connect/ from the index.html file.

Example of it after enabling: http://ojlewis.github.io/HTML-SVG-connect/

**Comment by a115** [comment]
Thank you @ojlewis ! This has been done - published at: http://a115.co.uk/HTML-SVG-connect/ 

Closing this issue now.
