### ISSUE TITLE
Reduce Radius of Arc

### ISSUE THREAD

**Issue by thezenmonkey** [a115/HTML-SVG-connect#7]
I was wondering how can I reduce teh radius of the arcs corners, or even change them into corners?

**Comment by ojlewis** [comment]
There's a scaling factor in the _drawPath_ function, which sets the values of _deltaX_ and _deltaY_ (on lines 163/164 in [jquery.html-svg-connect.js](https://github.com/a115/HTML-SVG-connect/blob/master/jquery.html-svg-connect.js#L163)).

It's set to **0.15**, so reducing the value reduces the arc radius (0 removes the arc) -- though bear in mind that this moves the 'turning' point of the path closer to the start point, so the _offset_ property for the path would need to be adjusted to compensate.

**Comment by thezenmonkey** [comment]
I figured out the math in the end and removed the scale factor all together in this fork [https://github.com/thezenmonkey/HTML-SVG-connect ](https://github.com/thezenmonkey/HTML-SVG-connect )
